### PR TITLE
LLVM Plugin Refactor + Corrected COFF Section Addresses

### LINKED ISSUE #516: Sections in PE32 and PE32+
In LLVM-3.4 COFF Binary Object produces incorrect addresses for symbols, segments and sections. The first two were fixed in #418, but sections were forgotten. So, they still have relative addresses, that doesn't intersect with address space of symbols, and as a result we have empty output when we try to print a disassembly of a program, e.g., 
```
bap -dasm bin/i686-w64-mingw32-echo
```
produces empty output.

### PR DESCRIPTION
**Pull request by parkre**
This PR resolve #516 and finish #517

### CODE REVIEW

File: plugins/llvm/llvm_binary.hpp [hunk 1]
```diff
@@ -434,39 +345,67 @@ using namespace llvm;
...
+section make_section(const coff_section &s, const uint64_t image_base) {
+    return section{s.Name, s.VirtualAddress + image_base, s.SizeOfRawData};
+}
+
+template <typename T>
+std::vector<section> readPE(const COFFObjectFile &obj, const T image_base) {
+    std::vector<section> sections;
+    for (auto it = obj.begin_sections();
+         it != obj.end_sections(); ++it) {
+        const coff_section *s = obj.getCOFFSection(it);
```
Comment (ivg) [inline plugins/llvm/llvm_binary.hpp]: shouldn't we check that the `coff_section` is not `null`? In the rest part of the code we do the check...

**Comment by ivg** [comment]
Ivan is happy now :)
